[package]
name = "senior-sage"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = "= 1.0.213"
serde_json = "= 1.0.132"
inputbot = "0.6.0"
once_cell = "1.20.1"
vosk = "0.2.0"
cpal = "0.15.3"
dasp = "0.11.0"
ragit = "0.3.4"
<<<<<<< HEAD
<<<<<<< HEAD
syn = "2.0.55"
=======
>>>>>>> efc05a9 (added rag)
=======
syn = "2.0.55"
>>>>>>> df7df33 (changes to dependencies)

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
